#!/bin/bash

# Save current version
NODE_VERSION=$(node --version)

source $NVM_DIR/nvm.sh

install() {
	nvm install 10

	# install with node v10
	nvm use 10

	# install deps
	npm ci

	# Restore current version
	nvm use $NODE_VERSION
}

build() {
	# Builds with node v10
	nvm use 10

	# actual build
	npm run build

	# Restore current version
	nvm use $NODE_VERSION
}

test() {
	npm run test
}

lint() {
	npm run lint
}

coverage() {
	npm run coverage
	npm run coveralls
}

deploy() {
	mkdir tmp || true;

	# copy files for publish
	cp package.json tmp/package.json
	cp package-lock.json tmp/package-lock.json
	cp README.md tmp/README.md
	cp LICENSE tmp/LICENSE
	cp -r lib tmp/lib

	# move into publish directory
	cd tmp

	# Set the NPM access token we will use to publish.
	npm config set registry https://registry.npmjs.org/
	npm config set //registry.npmjs.org/:_authToken ${NPM_TOKEN}

	# dry publish run to 
	npm pack

	# publish
	npm publish $(ls json-stream-stringify-*.tgz)
}

# Loop over arguments
for var in "$@"
do
	# Check if the function exists (bash specific)
	if declare -f "$var" > /dev/null
	then
	# call argument
	"$var"
	else
	# Show a helpful error
	echo "'$var' is not a known function name in docker_fn.sh" >&2
	exit 1
	fi
done
