name: JsonStreamStringify-CI
on: [push, pull_request]
concurrency: 
  group: ${{ github.head_ref || 'push' }}
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: volta-cli/action@v1
      with:
        node-version: 16
    - uses: actions/cache@v2
      id: build-cache
      if: ${{ !env.ACT }}
      with:
        key: build-cache
        path: .
    - run: npm ci
    - run: npm run lint
    - run: npm run build
    - run: npx es-check es3 'lib/**/*.js'
    - run: cp -r copy_to_lib/* lib
    # install older mocha for node<14 tests
    - run: npm i mocha@3.5.3 --no-save
    - uses: montudor/action-zip@v1
      with:
        args: zip -0 -qq -r node_modules.zip node_modules
    - uses: actions/upload-artifact@v3
      with:
        name: node-modules-artifact
        retention-days: 1
        path: node_modules.zip
    - uses: actions/upload-artifact@v3
      with:
        name: coverage
        retention-days: 1
        path: coverage
    - uses: actions/upload-artifact@v3
      with:
        name: build-artifact
        retention-days: 1
        path: |
          package.json
          package-lock.json
          README.md
          LICENSE
          lib
          test

  coverage:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: build-artifact
    - uses: actions/download-artifact@v3
      with:
        name: node-modules-artifact
    - uses: montudor/action-zip@v1
      with:
        args: unzip -qq node_modules.zip -d .
    - uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm run coverage
    - name: Coveralls
      uses: coverallsapp/github-action@master
      if: secrets.GITHUB_TOKEN
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
  
  test:
    needs: build
    strategy:
      matrix:
        node: [ 0.12, 4, 10, 18 ] # 16 is tested by coverage in build stage
    runs-on: ubuntu-latest
    steps:
    - run: echo "Switching to NodeJS v.${{ matrix.node }}."
    - uses: actions/download-artifact@v3
      with:
        name: build-artifact
    - uses: actions/download-artifact@v3
      with:
        name: node-modules-artifact
    - uses: montudor/action-zip@v1
      with:
        args: unzip -qq node_modules.zip -d .
    - uses: volta-cli/action@v1
      with:
        node-version: ${{ matrix.node }}
    - run: volta run --node ${{ matrix.node }} npm test

  deploy:
    needs: [test, coverage]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/') && secrets.NPM_TOKEN
    steps:
    - uses: volta-cli/action@v1
      with:
        node-version: 16
    - uses: actions/download-artifact@v3
      with:
        name: build-artifact
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
